In [2]:
import pandas as pd

In [3]:
full = pd.read_parquet('full.parquet')
full

            CSN  Label                                               Text
0      98972695  False  ===Patient Info===\n\nAge: 32, Gender: F, Race...
1      98972704  False  ===Patient Info===\n\nAge: 72, Gender: F, Race...
2      98972716   True  ===Patient Info===\n\nAge: 81, Gender: F, Race...
3      98972727  False  ===Patient Info===\n\nAge: 80, Gender: F, Race...
4      98972737  False  ===Patient Info===\n\nAge: 64, Gender: F, Race...
...         ...    ...                                                ...
69704  99999916  False  ===Patient Info===\n\nAge: 50, Gender: F, Race...
69705  99999930  False  ===Patient Info===\n\nAge: 69, Gender: F, Race...
69706  99999943  False  ===Patient Info===\n\nAge: 73, Gender: F, Race...
69707  99999946  False  ===Patient Info===\n\nAge: 25, Gender: F, Race...
69708  99999964  False  ===Patient Info===\n\nAge: 70, Gender: F, Race...

[69709 rows x 3 columns]

In [4]:
print("Number of positive samples:", len(full[full["Label"] == True]))

Number of positive samples: 10376

In [2]:
stability_df = pd.read_parquet("stability.parquet")
stability_df.head(10)

,CSN,Label,TimeUpto,Text
0,98972695,False,111.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
1,98972695,False,112.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
2,98972695,False,113.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
3,98972695,False,114.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
4,98972695,False,121.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
5,98972695,False,122.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
6,98972695,False,124.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
7,98972695,False,131.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
8,98972695,False,132.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
9,98972695,False,134.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."

In [3]:
# split into val and test by 70-30 ratio
val_csns = pd.read_parquet("val.parquet")["CSN"].tolist()
test_csns = pd.read_parquet("test.parquet")["CSN"].tolist()

stability_val_df = stability_df[stability_df["CSN"].isin(val_csns)]
stability_test_df = stability_df[stability_df["CSN"].isin(test_csns)]

stability_val_df.to_parquet("stability_val.parquet")
stability_test_df.to_parquet("stability_test.parquet")
print(f"Validation set size: {len(stability_val_df)}")
print(f"Test set size: {len(stability_test_df)}")

Validation set size: 726106
Test set size: 308576

In [4]:
stability_val_df.head()

,CSN,Label,TimeUpto,Text
0,98972695,False,111.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
1,98972695,False,112.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
2,98972695,False,113.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
3,98972695,False,114.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."
4,98972695,False,121.0,"===Patient Info===\n\nAge: 32, Gender: F, Race..."